import{a as f,S as y,i as u}from"./assets/vendor-3h0fHshV.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const m=e=>`
      <a class="gallery-item" href="${e.largeImageURL}">
        <div class="photo-card">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
        </a>`,L="48302509-34d9f74736e571fd8f4b83a25",b="https://pixabay.com/api/",p=(e,r)=>{const o={params:{key:L,q:e,per_page:15,page:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return f.get(`${b}`,o)},h=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),i=document.querySelector(".js-load-more-btn");let n=1,l="",v=new y(".gallery-item",{captionsData:"alt",captionDelay:250});const w=e=>{c.innerHTML="<p>Loading images, please wait...</p>"},S=async e=>{try{if(e.preventDefault(),l=e.currentTarget.elements.user_query.value.trim(),l===""){u.error({message:"The search field cannot be empty!!"});return}n=1,w(!0),i.classList.add("is-hidden");const{data:r}=await p(l,n);if(r.totalHits===0){u.warning({message:"Sorry, there are no images matching your search query. Please try again!"}),c.innerHTML="",h.reset();return}r.totalHits>1&&(i.classList.remove("is-hidden"),i.addEventListener("click",g));const o=r.hits.map(a=>m(a)).join("");c.innerHTML=o,v.refresh()}catch(r){console.log(r)}};h.addEventListener("submit",S);const g=async e=>{try{n++;const{data:r}=await p(l,n),o=r.hits.map(t=>m(t)).join("");c.insertAdjacentHTML("beforeend",o);const a=Math.ceil(r.totalHits/15);n>=a&&(i.classList.add("is-hidden"),i.removeEventListener("click",g),u.info({message:"We're sorry, but you've reached the end of search results."})),E()}catch(r){console.log(r)}},E=()=>{const{height:e}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
