import{a as y,S as b,i as n}from"./assets/vendor-3h0fHshV.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const g=e=>`
      <a class="gallery-item" href="${e.largeImageURL}">
        <div class="photo-card">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
        </a>`,L="48302509-34d9f74736e571fd8f4b83a25",w="https://pixabay.com/api/",f=(e,r)=>{const s={params:{key:L,q:e,per_page:15,page:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return y.get(`${w}`,s)},v=document.querySelector(".js-search-form"),d=document.querySelector(".js-gallery"),u=document.querySelector(".js-load-more-btn");let i=1,l="",p=new b(".js-gallery a",{captionsData:"alt",captionDelay:250});const c=e=>{e?u.classList.remove("is-hidden"):u.classList.add("is-hidden")},E=async e=>{try{if(e.preventDefault(),l=e.currentTarget.elements.user_query.value.trim(),l===""){n.error({message:"The search field cannot be empty!"});return}i=1,d.innerHTML="",c(!1);const{data:r}=await f(l,i);if(r.totalHits===0){n.warning({message:"No images found. Please try another search query!"});return}const s=r.hits.map(a=>g(a)).join("");d.innerHTML=s,p.refresh(),r.hits.length<15?c(!1):(c(!0),u.removeEventListener("click",h),u.addEventListener("click",h)),n.success({message:`Hooray! We found ${r.totalHits} images.`})}catch(r){n.error({title:"Error",message:"Something went wrong. Please check your internet connection or try again later."}),console.log("Error details:",r)}},h=async()=>{try{i++;const{data:e}=await f(l,i),r=e.hits.map(a=>g(a)).join("");d.insertAdjacentHTML("beforeend",r),p.refresh();const s=Math.ceil(e.totalHits/15);(i>=s||e.hits.length<15)&&(c(!1),n.info({message:"We're sorry, but you've reached the end of search results."})),S()}catch(e){n.error({title:"Error",message:"Something went wrong. Please check your internet connection or try again later."}),console.log("Error details:",e)}},S=()=>{const{height:e}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};v.addEventListener("submit",E);
//# sourceMappingURL=index.js.map
